name: cliffordep
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - pytest
  - scipy
  - snakeviz
  - statsmodels
  - tqdm
  - hatch
  - pip
  - pip:
      - ldpc
      - pymatching
      - stim
      - symft