[project]
name = "cliffordea"
version = "0.18.11"
description = "A Python package to analyze Clifford errors in quantum error correction circuits."
authors = [{name="Tim Chan", email="timwlc@icloud.com"}]
license = "MIT"
dependencies = [
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "pandas",
    "pytest",
    "scipy",
    "snakeviz",
    "statsmodels",
    "ldpc",
    "pymatching",
    "stim",
    "tqdm",
    "symft",
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
