[project]
name = "cliffordep"
version = "0.1.0"
description = "A Python package to analyze the propagation of Clifford errors."
authors = [{name="Tim Chan", email="timwlc@icloud.com"}]
dependencies = [
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "pandas",
    "pytest",
    "scipy",
    "snakeviz",
    "statsmodels",
    "ldpc",
    "pymatching",
    "stim"
]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["cliffordep*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"