[project]
name = "cliffordep"
version = "0.1.2"
description = "A Python package to analyze the propagation of Clifford errors."
authors = [{name="Tim Chan", email="timwlc@icloud.com"}]
dependencies = [
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "pandas",
    "pytest",
    "scipy",
    "snakeviz",
    "statsmodels",
    "ldpc",
    "pymatching",
    "stim"
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"