import pytest

from cliffordep.combinators import FaultCombinator
from cliffordep.type_aliases import LogicalTriple


@pytest.mark.parametrize("state", ['S', 'T'])
def test_superposition_vs_clifford(
        state,
        d3_combinator_and_kept_strings_by_analyzer: tuple[
            FaultCombinator,
            dict[str, list[dict[str, LogicalTriple]]],
            dict[str, list[dict[str, LogicalTriple]]],
        ],
):
    """Compare both analyzers' distance-3 results through order three.

    :param state: The cultivated S or T state whose results are compared.
    :param d3_combinator_and_kept_strings_by_analyzer: Session-scoped
        combinator and kept-string results generated by both analyzers.
    """
    _, superposition_results, clifford_results = (
        d3_combinator_and_kept_strings_by_analyzer
    )
    superposition_kept_strings = superposition_results[state]
    clifford_kept_strings = clifford_results[state]
    for degree, superposition_strings in enumerate(superposition_kept_strings):
        for kept_string, superposition_triple in superposition_strings.items():
            assert kept_string in clifford_kept_strings[degree], (
                f"{kept_string} missing in clifford_kept_strings[{degree}]"
            )
            clifford_triple = clifford_kept_strings[degree][kept_string]
            assert superposition_triple == clifford_triple, f"Mismatch for {kept_string}: {superposition_triple} vs {clifford_triple}"
        for kept_string in clifford_kept_strings[degree]:
            assert kept_string in superposition_strings, (
                f"{kept_string} missing in superposition_kept_strings[{degree}]"
            )

    # Correct result:
    # S state cultivation: for order...
    #     0, 1.0 (0.0) errors are kept and lead to identity (error).
    #     1, 2.0 (0.0) errors are kept and lead to identity (error).
    #     2, 6.0 (0.0) errors are kept and lead to identity (error).
    #     3, 16.0 (24.0) errors are kept and lead to identity (error).
    # T state cultivation: for order...
    #     0, 1.0 (0.0) errors are kept and lead to identity (error).
    #     1, 2.0 (0.0) errors are kept and lead to identity (error).
    #     2, 2.75 (1.0) errors are kept and lead to identity (error).
    #     3, 18.5 (23.75) errors are kept and lead to identity (error).
