import pytest

from cliffordea.accept.types import PauliMask
from cliffordea.enum import circuits, noise
from cliffordea.enum.combinators import FaultCombinator
from cliffordea.accept.logical_analyzers import CliffordLogicalAnalyzer
from cliffordea.enum.types import LogicalTriple


@pytest.mark.parametrize("state", ['S', 'T'])
def test_superposition_vs_clifford(
        state,
        d3_combinator_and_kept_effects_by_analyzer: tuple[
            FaultCombinator,
            dict[str, list[dict[PauliMask, LogicalTriple]]],
            dict[str, list[dict[PauliMask, LogicalTriple]]],
        ],
):
    """Compare both analyzers' distance-3 results through order three.

    :param state: The cultivated S or T state whose results are compared.
    :param d3_combinator_and_kept_effects_by_analyzer: Session-scoped
        combinator and kept-effect results generated by both analyzers.
    """
    _, superposition_results, clifford_results = (
        d3_combinator_and_kept_effects_by_analyzer
    )
    superposition_kept_effects = superposition_results[state]
    clifford_kept_effects = clifford_results[state]
    for degree, superposition_effects in enumerate(superposition_kept_effects):
        for kept_effect, superposition_triple in superposition_effects.items():
            assert kept_effect in clifford_kept_effects[degree], (
                f"{kept_effect} missing in clifford_kept_effects[{degree}]"
            )
            clifford_triple = clifford_kept_effects[degree][kept_effect]
            assert superposition_triple == clifford_triple, (
                f"Mismatch for {kept_effect}: "
                f"{superposition_triple} vs {clifford_triple}"
            )
        for kept_effect in clifford_kept_effects[degree]:
            assert kept_effect in superposition_effects, (
                f"{kept_effect} missing in superposition_kept_effects[{degree}]"
            )

    # Correct result:
    # S state cultivation: for order...
    #     0, 1.0 (0.0) errors are kept and lead to identity (error).
    #     1, 2.0 (0.0) errors are kept and lead to identity (error).
    #     2, 6.0 (0.0) errors are kept and lead to identity (error).
    #     3, 16.0 (24.0) errors are kept and lead to identity (error).
    # T state cultivation: for order...
    #     0, 1.0 (0.0) errors are kept and lead to identity (error).
    #     1, 2.0 (0.0) errors are kept and lead to identity (error).
    #     2, 2.75 (1.0) errors are kept and lead to identity (error).
    #     3, 18.5 (23.75) errors are kept and lead to identity (error).


def test_d5_factored_transversal_matches_general_workflow():
    """Factoring preserves every D5 kept effect through order four.

    :return: None.
    """
    circuit = circuits.DoubleCheck(distance=5, ancilla_count=19)
    noisy_circuit = noise.uniformly_depolarize(
        circuit.INNER_CIRCUIT,
        noise_level=1e-3,
    )
    combinator = FaultCombinator(noisy_circuit)
    analyzer_arguments = {
        'data_indices': circuit.DATA_INDICES,
        'stabilizer_generators': circuit.STABILIZER_GENERATORS_RESTRICTED,
        'logical_s': circuit.LOGICAL_S,
    }
    factored_results = combinator.get_kept_effects(
        logical_analyzer=CliffordLogicalAnalyzer(
            **analyzer_arguments,
            factor_transversal_errors=True,
        ),
        max_order=4,
        cultivated_states=('S', 'T'),
    )
    general_results = combinator.get_kept_effects(
        logical_analyzer=CliffordLogicalAnalyzer(
            **analyzer_arguments,
            factor_transversal_errors=False,
        ),
        max_order=4,
        cultivated_states=('S', 'T'),
    )

    assert factored_results == general_results
